version: "3"
services:
  executor:
    image: registry.gitlab.com/scalifyme/like/executor
    build: .
    networks:
      - like
    environment:
      - "NODE_ENV=dev"
      - "CHROME_HEADLESS=true"
      - "AWS_SQS_REGION=elasticmq"
      - "AWS_SECRET_ACCESS_KEY=x"
      - "AWS_ACCESS_KEY_ID=x"
      - "AWS_SQS_QUEUE_URL=http://queue:9324/queue/germany"
      - "AWS_SQS_VISIBILITY_TIMEOUT=300"
networks:
  like:
    external: true
