version: '3.5'
services:
  executor:
    image: registry.gitlab.com/scalifyme/like/executor
    build: .
    networks:
      - puppet_master
    environment:
      - "NODE_ENV=dev"
      - "CHROMIUM_HEADLESS=true"
      - "CHROMIUM_EXTRA_ARGS=[\"--proxy-server=socks5://vpn:8080\",\"--host-resolver-rules=MAP * ~NOTFOUND , EXCLUDE myproxy\",\"--ignore-certificate-errors\"]"
      - "QUEUE_HOST=queue"
      - "QUEUE_PORT=5672"
      - "QUEUE_USERNAME=puppet"
      - "QUEUE_PASSWORD=puppet"
    volumes:
      - "./data:/data"
networks:
  puppet_master:
    external: true
    name: puppet_master
