version: '3.5'
services:
  executor:
    image: registry.gitlab.com/scalifyme/like/executor
    build: .
    networks:
      - puppet_master
    environment:
      - "NODE_ENV=dev"
      - "CHROME_HEADLESS=true"
      - "QUEUE_HOST=queue"
      - "QUEUE_PORT=5672"
      - "QUEUE_USERNAME=puppet"
      - "QUEUE_PASSWORD=puppet"
    volumes:
      - "./data:/data"
networks:
  puppet_master:
    external: true
    name: puppet_master
